# Generated by Django 5.0.6 on 2024-11-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prev_extendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_valores', models.IntegerField(blank=None, default=0)),
                ('cidade', models.CharField(default='desconhecida', max_length=100)),
                ('sigla', models.CharField(default='desconhecida', max_length=50)),
                ('data_prev', models.CharField(default='00/00/00', max_length=50)),
                ('max_diaria', models.IntegerField(default=0)),
                ('min_diaria', models.IntegerField(default=0)),
            ],
        ),
    ]
