# Generated by Django 5.1 on 2024-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_info_clima_cidade_data_prev0'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_clima_cidade',
            name='estado',
            field=models.CharField(default='desconhecido', max_length=10),
        ),
    ]
