# Generated by Django 5.1 on 2024-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_clima_cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(default='Desconhecido', max_length=50)),
                ('temp_max', models.CharField(max_length=50)),
                ('temp_min', models.CharField(max_length=50)),
                ('ind_uv', models.CharField(max_length=50)),
                ('data_prev', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
