# Generated by Django 5.1 on 2024-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_info_clima_cidade_temp_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_clima_cidade',
            name='ind_uv',
            field=models.IntegerField(default=0),
        ),
    ]
