# Generated by Django 5.1 on 2024-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_info_clima_cidade_ind_uv'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_clima_cidade',
            name='data_prev0',
            field=models.CharField(default='22/10/2024', max_length=50),
        ),
    ]
